### ISSUE TITLE
[BUG]: strokes rendered at an offset position

### ISSUE THREAD

**Issue by Stiffpixels** [singodiyashubham87/Draw-it-out#117]
**Describe the bug**
When you scroll the screen on mobile and try to draw the strokes are rendered a little bit above where you are touching on the screen.

**To Reproduce**
1. Go to [draw it out website on mobile](https://draw-it-out.vercel.app/).
2. Scroll down a little bit.
3. Try drawing.
4. See error.

**Expected behavior**
the strokes should appear with correct position on the whiteboard.

**Screenshots**
here is a video showing the bug tried it on my phone as well:

**Additional context**

https://github.com/singodiyashubham87/Draw-it-out/assets/32983571/0e24af67-20e7-41e3-b7f6-d7034239dfa0

Assign this issue to me under gssoc24'

**Comment by 0xabdulkhalid** [comment]
This bug must needs to be fixed, I'm assigning this ISSUE to you @Stiffpixels.

You can start working!

**Comment by Stiffpixels** [comment]
> This bug must needs to be fixed, I'm assigning this ISSUE to you @Stiffpixels.
> 
> You can start working!

That issue is fixed now, Please assign me #130 instead.

**Comment by 0xabdulkhalid** [comment]
No @Stiffpixels, the bug is still there.

See here,

https://github.com/singodiyashubham87/Draw-it-out/assets/92252895/81e2346f-2043-4aa3-b503-db8aa78cd2c5

If you're not willing to work that's fine. We can assign any other person who are interested to work on this issue. Thank you!

**Comment by Stiffpixels** [comment]
> No @Stiffpixels, the bug is still there.
> 
> See here,
> 
> https://github.com/singodiyashubham87/Draw-it-out/assets/92252895/81e2346f-2043-4aa3-b503-db8aa78cd2c5
> 
> If you're not willing to work that's fine. We can assign any other person who are interested to work on this issue. Thank you!

That is when you switch to mobile while you are drawing. The issue I mentioned was occuring when you are on mobile and scroll down which causes the strokes to occur above where you are touching.

**Comment by 0xabdulkhalid** [comment]
You're right @Stiffpixels, Let me close this one as fixed.
